apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        volumeMounts:
        - name: redis
          mountPath: "/etc/redis"
        volumeMounts:
        - name: mongo
          mountPath: "/etc/mongo"
        volumeMounts:
        - name: db
          mountPath: "/etc/db"
        volumeMounts:
        - name: mailer
          mountPath: "/etc/mailer"
        env:
        - name: NAMESPACE
          value: "{{.Release.Namespace}}"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: "{{.Release.Namespace}}-fecache"
              key: redis-password
        - name: DB_CONN
          valueFrom:
            secretKeyRef: 
              name: "{{.Release.Namespace}}-pulsedb"
              key: connstr
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: "{{.Release.Namespace}}-mailer"
              key: mailuser
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: "{{.Release.Namespace}}-mailer"
              key: mailpassword
        - name: MAIL_HOST
          value: "smtp.gmail.com"
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_FROM
          value: "rmcloudsoftware@rareminds.in"
        - name: DB1_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: "{{.Release.Namespace}}-db1"
              key: mongodb-root-password
{{- if .Values.env}}
{{ toYaml .Values.env | indent 8 }}
{{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      - name: redis
        secret:
          secretName: "{{.Release.Namespace}}-fecache"
      - name: mongo
        secret:
          secretName: "{{.Release.Namespace}}-db1"
      - name: db
        secret:
          secretName: "{{.Release.Namespace}}-pulsedb"
      - name: mailer
        secret:
          secretName: "{{.Release.Namespace}}-mailer"
